### ISSUE TITLE
Journal Save Problem

### ISSUE THREAD

**Issue by julieduersch** [omkarlinux/jiggyjournal#81]
Journal Save says it was "saved successfully" but the list view remains empty.

**Comment by omkarlinux** [comment]
@julieduersch can you describe it more details on which browser you used? Which page you were on ?
Basically, steps that could help us re-create the problem.

I tried doing it at my end in both create and edit mode and it worked.

**Comment by julieduersch** [comment]
Chrome
journal entry window
I entered the title, date, entry and hit save
"Saved successfully" message appears
Redirected to list view page but no entry shows up
This is for user Dragon Team5

Does that help?

**Comment by omkarlinux** [comment]
@julieduersch Hmm Neetha and I tried it in Chrome and Firefox with the user dragonteam5 and also with our own accounts. It works.

Maybe it's a Cookie :) problem. Try clearing your cookies and try again.

**Comment by julieduersch** [comment]
Clearing the cookies solved it!

**Comment by Neethareddysama** [comment]
awesome!! we can now close this issue.
