### ISSUE TITLE
FAQ Final Changes

### ISSUE THREAD

**Issue by julieduersch** [omkarlinux/jiggyjournal#82]
Can we make the following changes (for grammar) on our FAQ page?
How to contact Jiggy Journal team?
Question should read:  How do I contact the Jiggy Journal team?
Answer should read:  You can reach us by providing your details and a short message in the Contact section.

What's the size of photos can I upload?
Question should read:  What size photos can I upload?
Answer should read:  Photos can be up to [whatever we can take goes here].

**Comment by omkarlinux** [comment]
Thanks for pointing that out @julieduersch!
