### ISSUE TITLE
Journal Entries Don't Save

### ISSUE THREAD

**Issue by julieduersch** [omkarlinux/jiggyjournal#88]
Not only am I not getting a "successful save" message when I save a journal entry, but it doesn't seem to be saving at all.  When I tried to save my entry it sent me to the list view page and the entry wasn't there.

**Comment by omkarlinux** [comment]
@julieduersch did you try clearing the cookies again?

**Comment by julieduersch** [comment]
Yes, still not saving, despite the "save successful" message.  It is showing up in the database?

**Comment by omkarlinux** [comment]
@julieduersch Okay, which email are you using for login?

**Comment by omkarlinux** [comment]
It doesn't show any new entries in the database too. But seems to be working fine for others.

**Comment by julieduersch** [comment]
I'm using the julieduersch@gmail.com and no matter which browser I use (IE, Firefox or Chrome) on my laptop or from my desktop, it doesn't save.  I can edit and save those changes, but I cannot create a new entry.

**Comment by omkarlinux** [comment]
@julieduersch does it allow you to create an entry with another email id?
