### ISSUE TITLE
Jiggy Journal logo isn't appearing in Chrome (it is appearing in IE and Firefox, even after I cleared cookies in IE and Firefox)

### ISSUE THREAD

**Issue by julieduersch** [omkarlinux/jiggyjournal#90]
The Jiggy Journal logo didn't automatically appear in Chrome.
![jiggyjournal broken link capture](https://cloud.githubusercontent.com/assets/18296597/14816293/31142cc4-0b6d-11e6-9ad7-91595d55ea08.PNG)
It does appear in IE and Firefox (even after I clear cookies).  When I clicked the broken link icon on the header bar in Chrome, it appeared and now appears when I load the page.  Should we be concerned?

**Comment by omkarlinux** [comment]
@julieduersch, we've always seen the icom during testing. Let us know if it becomes more frequent.
